version: "3"

services:
  db:
    container_name: itemz-db
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: itemz-db